# solr.yaml
# --------
# PURPOSE:
# Solr provides search indexing for Catalog service.
# We use:
# - Service: stable DNS name "solr" inside the cluster
# - StatefulSet + PVC: keep Solr index data persistent
#
# IMPORTANT:
# Solr is Java-based.
# We must control heap size AND container memory limits
# to avoid OOMKilled in dev environment.

apiVersion: v1
kind: Service
metadata:
  name: solr
spec:
  selector:
    app: solr
  ports:
    - name: http
      port: 8983
      targetPort: 8983

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solr
spec:
  serviceName: solr
  replicas: 1
  selector:
    matchLabels:
      app: solr
  template:
    metadata:
      labels:
        app: solr
    spec:
      containers:
        - name: solr
          image: solr:9
          args: ["solr-precreate", "products"]

          ports:
            - containerPort: 8983
              name: http

          #  Limit JVM heap explicitly
          # 256m heap is safe for dev
          env:
            - name: SOLR_JAVA_MEM
              value: "-Xms256m -Xmx256m"

          #  Balanced memory configuration
          # Heap 256m + JVM overhead ~100–150m
          # So container limit must be > 400Mi
          resources:
            requests:
              cpu: "80m"
              memory: "450Mi"
            limits:
              cpu: "200m"
              memory: "650Mi"

          volumeMounts:
            - name: solr-data
              mountPath: /var/solr

  volumeClaimTemplates:
    - metadata:
        name: solr-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi