# solr.yaml
# --------
# PURPOSE:
# Solr provides search indexing for Catalog service.
# We use:
# - Service: stable DNS name "solr" inside the cluster
# - StatefulSet + PVC: keep Solr index data persistent
#
# IMPORTANT:
# Solr is Java-based. If we don't limit heap, it can OOM in small dev quotas.
# SOLR_JAVA_MEM forces heap size to stay small.

apiVersion: v1
kind: Service
metadata:
  name: solr
spec:
  selector:
    app: solr
  ports:
    - name: http
      port: 8983
      targetPort: 8983

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solr
spec:
  serviceName: solr
  replicas: 1
  selector:
    matchLabels:
      app: solr
  template:
    metadata:
      labels:
        app: solr
    spec:
      containers:
        - name: solr
          image: solr:9
          args: ["solr-precreate", "products"]
          ports:
            - containerPort: 8983
              name: http

          #  Force small heap (most important fix for OOMKilled)
          env:
            - name: SOLR_JAVA_MEM
              value: "-Xms192m -Xmx192m"

          #  Very small resources to fit dev quota (1 CPU / 2Gi total)
          resources:
            requests:
              cpu: "60m"
              memory: "200Mi"
            limits:
              cpu: "80m"
              memory: "240Mi"

          volumeMounts:
            - name: solr-data
              mountPath: /var/solr

  volumeClaimTemplates:
    - metadata:
        name: solr-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
