apiVersion: v1
kind: Service
metadata:
  name: shopsphere-frontend
spec:
  selector:
    app: shopsphere-frontend

  ports:
    - name: http
      port: 3000
      targetPort: 3000
   

  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopsphere-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopsphere-frontend
  template:
    metadata:
      labels:
        app: shopsphere-frontend
    spec:
      containers:
        - name: shopsphere-frontend
          image: leunoraseferi/shopsphere-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: PORT
              value: "3000"
            - name: GATEWAY_URL
              value: "http://gateway:4000"
            - name: NEXT_PUBLIC_GATEWAY_URL
              value: "http://gateway:4000"
          resources:
            requests:
              cpu: "80m"
              memory: "200Mi"
            limits:
              cpu: "100m"
              memory: "250Mi"


