# quota-staging.yaml
# ------------------
# PURPOSE:
# Staging is "bigger than dev" (double resources).
# Production will have NO quota (as requested by the rubric).

apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-quota
spec:
  hard:
    requests.cpu: "3"
    requests.memory: "6Gi"
    limits.cpu: "3"
    limits.memory: "6Gi"

